version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.2
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: "1"
      - run: sudo ./initialize_script.sh
      - run: sudo timeout 45m ./build.sh bramble userdebug || true
      - save_cache:
          key: "1"
          paths:
            - "/tmp/ccache"